//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchShell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langauge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langauge() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchShell.Resources.Langauge", typeof(Langauge).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Taufiq Abdur Rahman.
        /// </summary>
        internal static string App_DeveloperCredit {
            get {
                return ResourceManager.GetString("App_DeveloperCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud settings deleted successfully.
        /// </summary>
        internal static string CloudSync_CloudSettingsDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CloudSync_CloudSettingsDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict resolution error: {0}.
        /// </summary>
        internal static string CloudSync_ConflictResolutionError {
            get {
                return ResourceManager.GetString("CloudSync_ConflictResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom settings not provided.
        /// </summary>
        internal static string CloudSync_CustomSettingsNotProvided {
            get {
                return ResourceManager.GetString("CloudSync_CustomSettingsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete error: {0}.
        /// </summary>
        internal static string CloudSync_DeleteError {
            get {
                return ResourceManager.GetString("CloudSync_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed: {0}.
        /// </summary>
        internal static string CloudSync_DeleteFailed {
            get {
                return ResourceManager.GetString("CloudSync_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: {0}.
        /// </summary>
        internal static string CloudSync_DownloadError {
            get {
                return ResourceManager.GetString("CloudSync_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed: {0}.
        /// </summary>
        internal static string CloudSync_DownloadFailed {
            get {
                return ResourceManager.GetString("CloudSync_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud encryption keys not available. Please re-enter your password to enable cloud sync..
        /// </summary>
        internal static string CloudSync_EncryptionKeysNotAvailable {
            get {
                return ResourceManager.GetString("CloudSync_EncryptionKeysNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud encryption keys not available. Please login again to enable cloud sync..
        /// </summary>
        internal static string CloudSync_EncryptionKeysNotAvailableLogin {
            get {
                return ResourceManager.GetString("CloudSync_EncryptionKeysNotAvailableLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get cloud settings.
        /// </summary>
        internal static string CloudSync_FailedToGetCloudSettings {
            get {
                return ResourceManager.GetString("CloudSync_FailedToGetCloudSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resolution option.
        /// </summary>
        internal static string CloudSync_InvalidResolutionOption {
            get {
                return ResourceManager.GetString("CloudSync_InvalidResolutionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local changes detected. Resolve conflicts first..
        /// </summary>
        internal static string CloudSync_LocalChangesDetected {
            get {
                return ResourceManager.GetString("CloudSync_LocalChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cloud settings found.
        /// </summary>
        internal static string CloudSync_NoCloudSettingsFound {
            get {
                return ResourceManager.GetString("CloudSync_NoCloudSettingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings downloaded from cloud successfully.
        /// </summary>
        internal static string CloudSync_SettingsDownloadedFromCloud {
            get {
                return ResourceManager.GetString("CloudSync_SettingsDownloadedFromCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings synced to cloud successfully.
        /// </summary>
        internal static string CloudSync_SettingsSyncedToCloud {
            get {
                return ResourceManager.GetString("CloudSync_SettingsSyncedToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync conflict detected.
        /// </summary>
        internal static string CloudSync_SyncConflictDetected {
            get {
                return ResourceManager.GetString("CloudSync_SyncConflictDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync error: {0}.
        /// </summary>
        internal static string CloudSync_SyncError {
            get {
                return ResourceManager.GetString("CloudSync_SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed.
        /// </summary>
        internal static string CloudSync_SyncFailed {
            get {
                return ResourceManager.GetString("CloudSync_SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed: {0}.
        /// </summary>
        internal static string CloudSync_SyncFailedWithStatus {
            get {
                return ResourceManager.GetString("CloudSync_SyncFailedWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated.
        /// </summary>
        internal static string CloudSync_UserNotAuthenticated {
            get {
                return ResourceManager.GetString("CloudSync_UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to {0} ({1}:{2}).
        /// </summary>
        internal static string Connection_AttemptingTo {
            get {
                return ResourceManager.GetString("Connection_AttemptingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string Connection_ConnectingTo {
            get {
                return ResourceManager.GetString("Connection_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing current tab.
        /// </summary>
        internal static string Connection_ErrorClosingTab {
            get {
                return ResourceManager.GetString("Connection_ErrorClosingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during control load.
        /// </summary>
        internal static string Connection_ErrorDuringControlLoad {
            get {
                return ResourceManager.GetString("Connection_ErrorDuringControlLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection to {0}....
        /// </summary>
        internal static string Connection_EstablishingConnection {
            get {
                return ResourceManager.GetString("Connection_EstablishingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to {0}:{1}.
        /// </summary>
        internal static string Connection_FailedTo {
            get {
                return ResourceManager.GetString("Connection_FailedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error handling connection timeout.
        /// </summary>
        internal static string Connection_HandleTimeoutError {
            get {
                return ResourceManager.GetString("Connection_HandleTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection health check failed - connection appears to be lost.
        /// </summary>
        internal static string Connection_HealthCheckFailed {
            get {
                return ResourceManager.GetString("Connection_HealthCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing file operations....
        /// </summary>
        internal static string Connection_InitializingFileOps {
            get {
                return ResourceManager.GetString("Connection_InitializingFileOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading home directory....
        /// </summary>
        internal static string Connection_LoadingHomeDirectory {
            get {
                return ResourceManager.GetString("Connection_LoadingHomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost - attempting to reconnect....
        /// </summary>
        internal static string Connection_Lost {
            get {
                return ResourceManager.GetString("Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting to {0}....
        /// </summary>
        internal static string Connection_Reconnecting {
            get {
                return ResourceManager.GetString("Connection_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnection failed: {0}.
        /// </summary>
        internal static string Connection_ReconnectionFailed {
            get {
                return ResourceManager.GetString("Connection_ReconnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up navigation....
        /// </summary>
        internal static string Connection_SettingUpNavigation {
            get {
                return ResourceManager.GetString("Connection_SettingUpNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected and initialized for {0}.
        /// </summary>
        internal static string Connection_SuccessfullyConnected {
            get {
                return ResourceManager.GetString("Connection_SuccessfullyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reconnected to {0}.
        /// </summary>
        internal static string Connection_SuccessfullyReconnected {
            get {
                return ResourceManager.GetString("Connection_SuccessfullyReconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ContextMenu_Download {
            get {
                return ResourceManager.GetString("ContextMenu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string ContextMenu_NewFolder {
            get {
                return ResourceManager.GetString("ContextMenu_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string ContextMenu_Rename {
            get {
                return ResourceManager.GetString("ContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ContextMenu_SelectAll {
            get {
                return ResourceManager.GetString("ContextMenu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ContextMenu_Upload {
            get {
                return ResourceManager.GetString("ContextMenu_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error in Dispose: {0} - {1}.
        /// </summary>
        internal static string Critical_ErrorInDispose {
            get {
                return ResourceManager.GetString("Critical_ErrorInDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string Dialog_Reconnect_ActionClose {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ActionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this connection tab and return to the dashboard.
        /// </summary>
        internal static string Dialog_Reconnect_ActionCloseDescription {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ActionCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Dialog_Reconnect_ActionReconnect {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ActionReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to reconnect to the server and resume your session.
        /// </summary>
        internal static string Dialog_Reconnect_ActionReconnectDescription {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ActionReconnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string Dialog_Reconnect_CloseButton {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to &apos;{0}&apos; ({1}:{2}) has timed out..
        /// </summary>
        internal static string Dialog_Reconnect_ConnectionTimedOutTemplate {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ConnectionTimedOutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server has timed out..
        /// </summary>
        internal static string Dialog_Reconnect_DefaultInfo {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_DefaultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection has been lost due to network timeout or server unavailability..
        /// </summary>
        internal static string Dialog_Reconnect_ErrorDetailsDefault {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ErrorDetailsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details:.
        /// </summary>
        internal static string Dialog_Reconnect_ErrorDetailsLabel {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_ErrorDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        internal static string Dialog_Reconnect_Header {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Dialog_Reconnect_PrimaryButton {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_PrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        internal static string Dialog_Reconnect_Question {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string Dialog_Reconnect_Title {
            get {
                return ResourceManager.GetString("Dialog_Reconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0} &apos;{1}&apos; here to upload.
        /// </summary>
        internal static string DragDrop_DropHere {
            get {
                return ResourceManager.GetString("DragDrop_DropHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0} item(s) here to upload.
        /// </summary>
        internal static string DragDrop_DropMultiple {
            get {
                return ResourceManager.GetString("DragDrop_DropMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) and {1} folder(s) will be uploaded.
        /// </summary>
        internal static string DragDrop_FilesAndFolders {
            get {
                return ResourceManager.GetString("DragDrop_FilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) will be uploaded.
        /// </summary>
        internal static string DragDrop_FilesOnly {
            get {
                return ResourceManager.GetString("DragDrop_FilesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be uploaded to current directory.
        /// </summary>
        internal static string DragDrop_FileToDirectory {
            get {
                return ResourceManager.GetString("DragDrop_FileToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder contents will be uploaded recursively.
        /// </summary>
        internal static string DragDrop_FolderRecursive {
            get {
                return ResourceManager.GetString("DragDrop_FolderRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder(s) will be uploaded recursively.
        /// </summary>
        internal static string DragDrop_FoldersOnly {
            get {
                return ResourceManager.GetString("DragDrop_FoldersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting up browser events.
        /// </summary>
        internal static string EventHandler_BrowserEventsSetupError {
            get {
                return ResourceManager.GetString("EventHandler_BrowserEventsSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser events set up successfully.
        /// </summary>
        internal static string EventHandler_BrowserEventsSetupSuccess {
            get {
                return ResourceManager.GetString("EventHandler_BrowserEventsSetupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error in exception handler: {0}.
        /// </summary>
        internal static string EventHandler_CriticalErrorInExceptionHandler {
            get {
                return ResourceManager.GetString("EventHandler_CriticalErrorInExceptionHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cancelled for: {0}.
        /// </summary>
        internal static string EventHandler_EditCancelled {
            get {
                return ResourceManager.GetString("EventHandler_EditCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in {0}.
        /// </summary>
        internal static string EventHandler_ExceptionIn {
            get {
                return ResourceManager.GetString("EventHandler_ExceptionIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in safe execute async.
        /// </summary>
        internal static string EventHandler_SafeExecuteAsyncError {
            get {
                return ResourceManager.GetString("EventHandler_SafeExecuteAsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in safe execute.
        /// </summary>
        internal static string EventHandler_SafeExecuteError {
            get {
                return ResourceManager.GetString("EventHandler_SafeExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select servers to export:.
        /// </summary>
        internal static string Export_SelectServers {
            get {
                return ResourceManager.GetString("Export_SelectServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Servers.
        /// </summary>
        internal static string Export_Title {
            get {
                return ResourceManager.GetString("Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        internal static string Export_ToFile {
            get {
                return ResourceManager.GetString("Export_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key Files (*.pem;*.key)|*.pem;*.key|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_PrivateKey {
            get {
                return ResourceManager.GetString("FileFilter_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key Files (*.pub)|*.pub|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_PublicKey {
            get {
                return ResourceManager.GetString("FileFilter_PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.ss)|*.ss|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_ScratchShell {
            get {
                return ResourceManager.GetString("FileFilter_ScratchShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        internal static string FileOp_ClipboardEmpty {
            get {
                return ResourceManager.GetString("FileOp_ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?
        ///
        ///This action cannot be undone..
        /// </summary>
        internal static string FileOp_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("FileOp_DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string FileOp_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("FileOp_DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following {0} item(s)?
        ///
        ///{1}
        ///
        ///This action cannot be undone..
        /// </summary>
        internal static string FileOp_DeleteMultiConfirmMessage {
            get {
                return ResourceManager.GetString("FileOp_DeleteMultiConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} selected items?
        ///
        ///{1}... and {2} more
        ///
        ///This action cannot be undone..
        /// </summary>
        internal static string FileOp_DeleteMultiConfirmMessageMany {
            get {
                return ResourceManager.GetString("FileOp_DeleteMultiConfirmMessageMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} items?.
        /// </summary>
        internal static string FileOp_DeleteMultiConfirmTitle {
            get {
                return ResourceManager.GetString("FileOp_DeleteMultiConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled by user.
        /// </summary>
        internal static string FileOp_DownloadCancelledByUser {
            get {
                return ResourceManager.GetString("FileOp_DownloadCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        internal static string FileOp_DownloadFile {
            get {
                return ResourceManager.GetString("FileOp_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop upload initiated for {0} item(s).
        /// </summary>
        internal static string FileOp_DragDropUploadInitiated {
            get {
                return ResourceManager.GetString("FileOp_DragDropUploadInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files provided for upload.
        /// </summary>
        internal static string FileOp_NoFilesForUpload {
            get {
                return ResourceManager.GetString("FileOp_NoFilesForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        internal static string FileOp_OperationCancelled {
            get {
                return ResourceManager.GetString("FileOp_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder for {0}.
        /// </summary>
        internal static string FileOp_SelectDestinationFolder {
            get {
                return ResourceManager.GetString("FileOp_SelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled by user.
        /// </summary>
        internal static string FileOp_UploadCancelledByUser {
            get {
                return ResourceManager.GetString("FileOp_UploadCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string FileOp_UploadFile {
            get {
                return ResourceManager.GetString("FileOp_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string General_Cancelled {
            get {
                return ResourceManager.GetString("General_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string General_Close {
            get {
                return ResourceManager.GetString("General_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string General_Edit {
            get {
                return ResourceManager.GetString("General_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string General_Error {
            get {
                return ResourceManager.GetString("General_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string General_Export {
            get {
                return ResourceManager.GetString("General_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string General_File {
            get {
                return ResourceManager.GetString("General_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string General_Folder {
            get {
                return ResourceManager.GetString("General_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string General_Import {
            get {
                return ResourceManager.GetString("General_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string General_Login {
            get {
                return ResourceManager.GetString("General_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string General_Logout {
            get {
                return ResourceManager.GetString("General_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string General_No {
            get {
                return ResourceManager.GetString("General_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string General_NotApplicable {
            get {
                return ResourceManager.GetString("General_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string General_OK {
            get {
                return ResourceManager.GetString("General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string General_Register {
            get {
                return ResourceManager.GetString("General_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string General_Sync {
            get {
                return ResourceManager.GetString("General_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string General_Yes {
            get {
                return ResourceManager.GetString("General_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Import_InvalidPassword {
            get {
                return ResourceManager.GetString("Import_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import_Title {
            get {
                return ResourceManager.GetString("Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বাংলা.
        /// </summary>
        internal static string Language_Bangla {
            get {
                return ResourceManager.GetString("Language_Bangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for the language change to take full effect..
        /// </summary>
        internal static string Language_ChangeMessage {
            get {
                return ResourceManager.GetString("Language_ChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting parent path for {0}.
        /// </summary>
        internal static string Navigation_ErrorGettingParentPath {
            get {
                return ResourceManager.GetString("Navigation_ErrorGettingParentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Navigation_Home {
            get {
                return ResourceManager.GetString("Navigation_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-select operation requested for {0} selected item(s).
        /// </summary>
        internal static string Navigation_MultiSelectOperation {
            get {
                return ResourceManager.GetString("Navigation_MultiSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-select operation failed: No items selected.
        /// </summary>
        internal static string Navigation_MultiSelectOperationFailed {
            get {
                return ResourceManager.GetString("Navigation_MultiSelectOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-select operation failed: No valid items selected.
        /// </summary>
        internal static string Navigation_MultiSelectOperationFailedValid {
            get {
                return ResourceManager.GetString("Navigation_MultiSelectOperationFailedValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to folder: {0}.
        /// </summary>
        internal static string Navigation_NavigatingToFolder {
            get {
                return ResourceManager.GetString("Navigation_NavigatingToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to parent directory: {0}.
        /// </summary>
        internal static string Navigation_NavigatingToParent {
            get {
                return ResourceManager.GetString("Navigation_NavigatingToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file: {0}.
        /// </summary>
        internal static string Navigation_OpeningFile {
            get {
                return ResourceManager.GetString("Navigation_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Navigation_Session {
            get {
                return ResourceManager.GetString("Navigation_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Navigation_Settings {
            get {
                return ResourceManager.GetString("Navigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling operation....
        /// </summary>
        internal static string Operation_Cancelling {
            get {
                return ResourceManager.GetString("Operation_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup completed successfully.
        /// </summary>
        internal static string Operation_CleanupCompleted {
            get {
                return ResourceManager.GetString("Operation_CleanupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing current tab due to connection failure.
        /// </summary>
        internal static string Operation_ClosingCurrentTab {
            get {
                return ResourceManager.GetString("Operation_ClosingCurrentTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error: {0}.
        /// </summary>
        internal static string Operation_ConnectionError {
            get {
                return ResourceManager.GetString("Operation_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout detected: {0}.
        /// </summary>
        internal static string Operation_ConnectionTimeoutDetected {
            get {
                return ResourceManager.GetString("Operation_ConnectionTimeoutDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering full screen mode.
        /// </summary>
        internal static string Operation_EnteringFullscreen {
            get {
                return ResourceManager.GetString("Operation_EnteringFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting full screen mode.
        /// </summary>
        internal static string Operation_ExitingFullscreen {
            get {
                return ResourceManager.GetString("Operation_ExitingFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during connection health check.
        /// </summary>
        internal static string Operation_HealthCheckError {
            get {
                return ResourceManager.GetString("Operation_HealthCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in progress....
        /// </summary>
        internal static string Operation_InProgress {
            get {
                return ResourceManager.GetString("Operation_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation log panel closed.
        /// </summary>
        internal static string Operation_LogPanelClosed {
            get {
                return ResourceManager.GetString("Operation_LogPanelClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation log panel opened.
        /// </summary>
        internal static string Operation_LogPanelOpened {
            get {
                return ResourceManager.GetString("Operation_LogPanelOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error: {0}.
        /// </summary>
        internal static string Operation_NetworkError {
            get {
                return ResourceManager.GetString("Operation_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH connection error: {0}.
        /// </summary>
        internal static string Operation_SSHConnectionError {
            get {
                return ResourceManager.GetString("Operation_SSHConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting cleanup and disconnection.
        /// </summary>
        internal static string Operation_StartingCleanup {
            get {
                return ResourceManager.GetString("Operation_StartingCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation timeout: {0}.
        /// </summary>
        internal static string Operation_Timeout {
            get {
                return ResourceManager.GetString("Operation_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface enabled - ready for file operations.
        /// </summary>
        internal static string Operation_UIEnabled {
            get {
                return ResourceManager.GetString("Operation_UIEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to encrypt the export file.
        /// </summary>
        internal static string Placeholder_ExportPassword {
            get {
                return ResourceManager.GetString("Placeholder_ExportPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password for encrypted key file (leave empty if key is not encrypted).
        /// </summary>
        internal static string Placeholder_KeyFilePassword {
            get {
                return ResourceManager.GetString("Placeholder_KeyFilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search snippets....
        /// </summary>
        internal static string Placeholder_SearchSnippets {
            get {
                return ResourceManager.GetString("Placeholder_SearchSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password (leave empty if using key file authentication).
        /// </summary>
        internal static string Placeholder_ServerPassword {
            get {
                return ResourceManager.GetString("Placeholder_ServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string Placeholder_Username {
            get {
                return ResourceManager.GetString("Placeholder_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH: Secure Shell for terminal access
        ///FTP: File Transfer Protocol
        ///SFTP: SSH File Transfer Protocol.
        /// </summary>
        internal static string Protocol_Description_Combined {
            get {
                return ResourceManager.GetString("Protocol_Description_Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP: File Transfer Protocol.
        /// </summary>
        internal static string Protocol_FTP_Description {
            get {
                return ResourceManager.GetString("Protocol_FTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP: SSH File Transfer Protocol.
        /// </summary>
        internal static string Protocol_SFTP_Description {
            get {
                return ResourceManager.GetString("Protocol_SFTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH: Secure Shell for terminal access.
        /// </summary>
        internal static string Protocol_SSH_Description {
            get {
                return ResourceManager.GetString("Protocol_SSH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Actions.
        /// </summary>
        internal static string Server_Actions {
            get {
                return ResourceManager.GetString("Server_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Server_Host {
            get {
                return ResourceManager.GetString("Server_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key File Password.
        /// </summary>
        internal static string Server_KeyFilePassword {
            get {
                return ResourceManager.GetString("Server_KeyFilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string Server_Name {
            get {
                return ResourceManager.GetString("Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Server_Port {
            get {
                return ResourceManager.GetString("Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        internal static string Server_PrivateKey {
            get {
                return ResourceManager.GetString("Server_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Server_Protocol {
            get {
                return ResourceManager.GetString("Server_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string Server_PublicKey {
            get {
                return ResourceManager.GetString("Server_PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server_Title {
            get {
                return ResourceManager.GetString("Server_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Key File Authentication.
        /// </summary>
        internal static string Server_UseKeyFileAuth {
            get {
                return ResourceManager.GetString("Server_UseKeyFileAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors:.
        /// </summary>
        internal static string Server_ValidationSummary {
            get {
                return ResourceManager.GetString("Server_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Settings_Account {
            get {
                return ResourceManager.GetString("Settings_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-sync on changes.
        /// </summary>
        internal static string Settings_AutoSyncChanges {
            get {
                return ResourceManager.GetString("Settings_AutoSyncChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-sync on startup.
        /// </summary>
        internal static string Settings_AutoSyncStartup {
            get {
                return ResourceManager.GetString("Settings_AutoSyncStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Sync.
        /// </summary>
        internal static string Settings_CloudSync {
            get {
                return ResourceManager.GetString("Settings_CloudSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Dark {
            get {
                return ResourceManager.GetString("Settings_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Shell.
        /// </summary>
        internal static string Settings_DefaultShell {
            get {
                return ResourceManager.GetString("Settings_DefaultShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cloud Data.
        /// </summary>
        internal static string Settings_DeleteCloudData {
            get {
                return ResourceManager.GetString("Settings_DeleteCloudData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Cloud Sync.
        /// </summary>
        internal static string Settings_EnableCloudSync {
            get {
                return ResourceManager.GetString("Settings_EnableCloudSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync: {0}.
        /// </summary>
        internal static string Settings_LastSync {
            get {
                return ResourceManager.GetString("Settings_LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Light {
            get {
                return ResourceManager.GetString("Settings_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Settings_Personalization {
            get {
                return ResourceManager.GetString("Settings_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        internal static string Snippet_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("Snippet_DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this snippet?.
        /// </summary>
        internal static string Snippet_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("Snippet_DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Snippets ({0}).
        /// </summary>
        internal static string Snippet_SystemSnippets {
            get {
                return ResourceManager.GetString("Snippet_SystemSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Snippets ({0}).
        /// </summary>
        internal static string Snippet_UserSnippets {
            get {
                return ResourceManager.GetString("Snippet_UserSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH terminal was not opened (admin permission was declined)..
        /// </summary>
        internal static string Status_CancelledSSHTerminalUAC {
            get {
                return ResourceManager.GetString("Status_CancelledSSHTerminalUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoComplete error: {0}.
        /// </summary>
        internal static string Terminal_AutoCompleteError {
            get {
                return ResourceManager.GetString("Terminal_AutoCompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string Terminal_ConnectingTo {
            get {
                return ResourceManager.GetString("Terminal_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to {0}: {1}.
        /// </summary>
        internal static string Terminal_ConnectionFailed {
            get {
                return ResourceManager.GetString("Terminal_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevated.
        /// </summary>
        internal static string Terminal_Elevated {
            get {
                return ResourceManager.GetString("Terminal_Elevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open terminal with administrator privileges.
        /// </summary>
        internal static string Terminal_ElevatedTooltip {
            get {
                return ResourceManager.GetString("Terminal_ElevatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Terminal_Error {
            get {
                return ResourceManager.GetString("Terminal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Terminal_Normal {
            get {
                return ResourceManager.GetString("Terminal_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open terminal with normal privileges.
        /// </summary>
        internal static string Terminal_NormalTooltip {
            get {
                return ResourceManager.GetString("Terminal_NormalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resize terminal: {0}.
        /// </summary>
        internal static string Terminal_ResizeFailed {
            get {
                return ResourceManager.GetString("Terminal_ResizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not initialized..
        /// </summary>
        internal static string Terminal_ServerNotInitialized {
            get {
                return ResourceManager.GetString("Terminal_ServerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal update error: {0}.
        /// </summary>
        internal static string Terminal_UpdateError {
            get {
                return ResourceManager.GetString("Terminal_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new server to your list.
        /// </summary>
        internal static string Tooltip_AddServer {
            get {
                return ResourceManager.GetString("Tooltip_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt+Left Arrow).
        /// </summary>
        internal static string Tooltip_Back {
            get {
                return ResourceManager.GetString("Tooltip_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for export file location.
        /// </summary>
        internal static string Tooltip_BrowseExportLocation {
            get {
                return ResourceManager.GetString("Tooltip_BrowseExportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        internal static string Tooltip_BrowseFile {
            get {
                return ResourceManager.GetString("Tooltip_BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for private key file.
        /// </summary>
        internal static string Tooltip_BrowsePrivateKey {
            get {
                return ResourceManager.GetString("Tooltip_BrowsePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for public key file.
        /// </summary>
        internal static string Tooltip_BrowsePublicKey {
            get {
                return ResourceManager.GetString("Tooltip_BrowsePublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string Tooltip_CloseTab {
            get {
                return ResourceManager.GetString("Tooltip_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected text from terminal (Ctrl+Left Click).
        /// </summary>
        internal static string Tooltip_CopyFromTerminal {
            get {
                return ResourceManager.GetString("Tooltip_CopyFromTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        internal static string Tooltip_CreateNewFolder {
            get {
                return ResourceManager.GetString("Tooltip_CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new snippet.
        /// </summary>
        internal static string Tooltip_CreateSnippet {
            get {
                return ResourceManager.GetString("Tooltip_CreateSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected snippet.
        /// </summary>
        internal static string Tooltip_DeleteSnippet {
            get {
                return ResourceManager.GetString("Tooltip_DeleteSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected snippet.
        /// </summary>
        internal static string Tooltip_EditSnippet {
            get {
                return ResourceManager.GetString("Tooltip_EditSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your server list to a file for backup or sharing.
        /// </summary>
        internal static string Tooltip_ExportServers {
            get {
                return ResourceManager.GetString("Tooltip_ExportServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt+Right Arrow).
        /// </summary>
        internal static string Tooltip_Forward {
            get {
                return ResourceManager.GetString("Tooltip_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen mode.
        /// </summary>
        internal static string Tooltip_FullScreenMode {
            get {
                return ResourceManager.GetString("Tooltip_FullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import servers from a file into your list.
        /// </summary>
        internal static string Tooltip_ImportServers {
            get {
                return ResourceManager.GetString("Tooltip_ImportServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new terminal session (choose mode).
        /// </summary>
        internal static string Tooltip_OpenTerminal {
            get {
                return ResourceManager.GetString("Tooltip_OpenTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string Tooltip_Paste {
            get {
                return ResourceManager.GetString("Tooltip_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text into terminal (Alt+Left Click).
        /// </summary>
        internal static string Tooltip_PasteToTerminal {
            get {
                return ResourceManager.GetString("Tooltip_PasteToTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        internal static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this snippet in the terminal.
        /// </summary>
        internal static string Tooltip_RunSnippet {
            get {
                return ResourceManager.GetString("Tooltip_RunSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search servers by name, host, or protocol.
        /// </summary>
        internal static string Tooltip_SearchServers {
            get {
                return ResourceManager.GetString("Tooltip_SearchServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide log panel.
        /// </summary>
        internal static string Tooltip_ShowHideLogPanel {
            get {
                return ResourceManager.GetString("Tooltip_ShowHideLogPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide command snippets panel.
        /// </summary>
        internal static string Tooltip_ShowHideSnippets {
            get {
                return ResourceManager.GetString("Tooltip_ShowHideSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide System Snippet.
        /// </summary>
        internal static string Tooltip_ShowHideSystemSnippets {
            get {
                return ResourceManager.GetString("Tooltip_ShowHideSystemSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide theming panel.
        /// </summary>
        internal static string Tooltip_ShowHideThemes {
            get {
                return ResourceManager.GetString("Tooltip_ShowHideThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle full screen mode for terminal.
        /// </summary>
        internal static string Tooltip_ToggleFullScreenTerminal {
            get {
                return ResourceManager.GetString("Tooltip_ToggleFullScreenTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up one level.
        /// </summary>
        internal static string Tooltip_UpOneLevel {
            get {
                return ResourceManager.GetString("Tooltip_UpOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View options.
        /// </summary>
        internal static string Tooltip_ViewOptions {
            get {
                return ResourceManager.GetString("Tooltip_ViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel current operation.
        /// </summary>
        internal static string UI_CancelOperation {
            get {
                return ResourceManager.GetString("UI_CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string UI_Date {
            get {
                return ResourceManager.GetString("UI_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string UI_DateModified {
            get {
                return ResourceManager.GetString("UI_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files and folders here to upload.
        /// </summary>
        internal static string UI_DragDropDefault {
            get {
                return ResourceManager.GetString("UI_DragDropDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files and folders are supported.
        /// </summary>
        internal static string UI_DragDropSupport {
            get {
                return ResourceManager.GetString("UI_DragDropSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View.
        /// </summary>
        internal static string UI_GridView {
            get {
                return ResourceManager.GetString("UI_GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        internal static string UI_ListView {
            get {
                return ResourceManager.GetString("UI_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UI_Name {
            get {
                return ResourceManager.GetString("UI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Log.
        /// </summary>
        internal static string UI_OperationLog {
            get {
                return ResourceManager.GetString("UI_OperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string UI_Password {
            get {
                return ResourceManager.GetString("UI_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string UI_Search {
            get {
                return ResourceManager.GetString("UI_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string UI_SelectAll {
            get {
                return ResourceManager.GetString("UI_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string UI_Size {
            get {
                return ResourceManager.GetString("UI_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending (click to sort descending).
        /// </summary>
        internal static string UI_SortAscending {
            get {
                return ResourceManager.GetString("UI_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string UI_SortBy {
            get {
                return ResourceManager.GetString("UI_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Newest first).
        /// </summary>
        internal static string UI_SortDateNewest {
            get {
                return ResourceManager.GetString("UI_SortDateNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (Oldest first).
        /// </summary>
        internal static string UI_SortDateOldest {
            get {
                return ResourceManager.GetString("UI_SortDateOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending (click to sort ascending).
        /// </summary>
        internal static string UI_SortDescending {
            get {
                return ResourceManager.GetString("UI_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (A to Z).
        /// </summary>
        internal static string UI_SortNameAZ {
            get {
                return ResourceManager.GetString("UI_SortNameAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Z to A).
        /// </summary>
        internal static string UI_SortNameZA {
            get {
                return ResourceManager.GetString("UI_SortNameZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort options.
        /// </summary>
        internal static string UI_SortOptions {
            get {
                return ResourceManager.GetString("UI_SortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Largest first).
        /// </summary>
        internal static string UI_SortSizeLargest {
            get {
                return ResourceManager.GetString("UI_SortSizeLargest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Smallest first).
        /// </summary>
        internal static string UI_SortSizeSmallest {
            get {
                return ResourceManager.GetString("UI_SortSizeSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (A to Z).
        /// </summary>
        internal static string UI_SortTypeAZ {
            get {
                return ResourceManager.GetString("UI_SortTypeAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (Z to A).
        /// </summary>
        internal static string UI_SortTypeZA {
            get {
                return ResourceManager.GetString("UI_SortTypeZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle sort direction.
        /// </summary>
        internal static string UI_ToggleSortDirection {
            get {
                return ResourceManager.GetString("UI_ToggleSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string UI_Type {
            get {
                return ResourceManager.GetString("UI_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UI_Username {
            get {
                return ResourceManager.GetString("UI_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP address (e.g., 192.168.1.100) or hostname (e.g., server.example.com).
        /// </summary>
        internal static string Validation_HostTooltip {
            get {
                return ResourceManager.GetString("Validation_HostTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter port number (1-65535). Common ports: SSH=22, FTP=21, SFTP=22.
        /// </summary>
        internal static string Validation_PortTooltip {
            get {
                return ResourceManager.GetString("Validation_PortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to your private key file (.pem, .key).
        /// </summary>
        internal static string Validation_PrivateKeyTooltip {
            get {
                return ResourceManager.GetString("Validation_PrivateKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the connection protocol.
        /// </summary>
        internal static string Validation_ProtocolTooltip {
            get {
                return ResourceManager.GetString("Validation_ProtocolTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to your public key file (.pub).
        /// </summary>
        internal static string Validation_PublicKeyTooltip {
            get {
                return ResourceManager.GetString("Validation_PublicKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username for the server.
        /// </summary>
        internal static string Validation_UsernameTooltip {
            get {
                return ResourceManager.GetString("Validation_UsernameTooltip", resourceCulture);
            }
        }
    }
}
